#! /usr/bin/env python
# encoding: utf-8
# :mode=python:  - For jedit

# Copyright (C) 2009 Daniel Prevost <dprevost@photonsoftware.org>
#  
# This file is free software; as a special exception the author gives
# unlimited permission to copy and/or distribute it, with or without 
# modifications, as long as this notice is preserved.
# 
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY, to the extent permitted by law; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

import os

subdirs_list = [
        'Api',
        'CommonObject',
        'Connector',
        'DataDefinition',
        'FastMap' ]

def build(bld):
   
   # build root, including the variant directory
   quasar_dir = os.path.join(os.path.join(bld.srcnode.abspath(bld.env), 'src'), 'Quasar')
   src_dir = bld.srcnode.abspath()

   obj = bld.new_task_gen('subst')
   obj.source = 'quasar-run.h.in'
   obj.target = 'quasar-run.h'
   obj.dict   = {'QUASAR_DIR': '"' + quasar_dir + '"', 'SRC_DIR': src_dir }
  
   bld.add_subdirs( subdirs_list )

