#! /usr/bin/env python
# encoding: utf-8
# :mode=python:  - For jedit

# Copyright (C) 2009 Daniel Prevost <dprevost@photonsoftware.org>
#  
# This file is free software; as a special exception the author gives
# unlimited permission to copy and/or distribute it, with or without 
# modifications, as long as this notice is preserved.
# 
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY, to the extent permitted by law; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

debugger_list = [
        'app.cpp',
        'folder.cpp',
        'frame.cpp',
        'listCtrl.cpp',
        'memoryFile.cpp',
        'memoryHeader.cpp',
        'node.cpp',
        'pso.cpp',
        'queue.cpp',
        'tree.cpp' ]

def build(bld):

   debugger_exe = bld.new_task_gen(
      features     = 'cxx cprogram',
      source       = debugger_list,
      includes     = '../.. ../../include',
      uselib_local = 'Common Nucleus',
      uselib       = 'WX',
      lib          = bld.env['CMOCKERY'],
      target       = 'psodbg')

   debugger_exe_release = debugger_exe.clone('release')

