#! /usr/bin/env python
# encoding: utf-8
# :mode=python:  - For jedit

# Copyright (C) 2009 Daniel Prevost <dprevost@photonsoftware.org>
#  
# This file is free software; as a special exception the author gives
# unlimited permission to copy and/or distribute it, with or without 
# modifications, as long as this notice is preserved.
# 
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY, to the extent permitted by law; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.


def build(bld):
   
   bld.new_task_gen( features    = 'javac seq',
                     source_root = 'java_src' )
   ''',
                     sourcepath  = ['java_src/photon', 'java_src/serializer'] )
   #'org/photon' )
   '''
   '''bld.new_task_gen( features = 'jar seq',
                     basedir  = 'java_src',
                     destfile = 'foo.jar')
   '''
   #jaropts = '-C default/src/ .', # can be used to give files
   #classpath = '..:.', # can be used to set a custom classpath
   #)
   jni_lib = bld.new_task_gen( features = 'cc cshlib',
                               includes = 'include .. ../include',
                               target   = 'photon_jni',
                               uselib   = 'JAVA' )
   jni_lib.find_sources_in_dirs('jni')

   jni_lib_release = jni_lib.clone('release')

   '''
   javah org.photon.FieldType
   
   javadoc -sourcepath java_src -d doc org.photon org.photon.serializer
   '''
