#! /usr/bin/env python
# encoding: utf-8
# :mode=python:  - For jedit

# Copyright (C) 2009 Daniel Prevost <dprevost@photonsoftware.org>
#  
# This file is free software; as a special exception the author gives
# unlimited permission to copy and/or distribute it, with or without 
# modifications, as long as this notice is preserved.
# 
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY, to the extent permitted by law; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

# See http://www.gnu.org/software/libtool/manual.html#SEC34
# for more info on version-info/vnum. 
# Hints:
#  - the version is not in synch with the version of the whole package
#  - format:  currentversion:revision:age  (age is the tricky one here)

api_list = [
        'api.c',
        'CommonObject.c',
        'Connector.c',
        'DataDefinition.c',
        'FastMap.c',
        'Folder.c',
        'HashMap.c',
        'KeyDefinition.c',
        'Lifo.c',
        'Process.c',
        'Queue.c',
        'Session.c',
        'Standalone.c']

def build(bld):
   api_lib = bld.new_task_gen(
      features     = 'cc cshlib',
      source       = api_list,
      includes     = '.. ../include',
      defines      = ['BUILD_PHOTON_API'],
      uselib_local = 'Common Nucleus',
      target       = 'photon',
      vnum         = '0.0.0'
   )
   api_lib_release = api_lib.clone('release')

   bld.add_subdirs(['Tests'])

