#! /usr/bin/env python
# encoding: utf-8
# :mode=python:  - For jedit

# Copyright (C) 2009 Daniel Prevost <dprevost@photonsoftware.org>
#  
# This file is free software; as a special exception the author gives
# unlimited permission to copy and/or distribute it, with or without 
# modifications, as long as this notice is preserved.
# 
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY, to the extent permitted by law; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

ctx.check_cc(
      fragment='''
         #include <stdio.h>
         #include <stdlib.h>
         #include <unistd.h>
         
         int main() {

            int rc = access("test", 0);

            return rc;
         }''',
      define_name='HAVE_ACCESS',
      execute=0,
      define_ret=0,
      msg='Checking for access')

ctx.check_cc(
      fragment='''
         #include <stdio.h>
         #include <stdlib.h>
         #include <io.h>
         
         int main() {

            int rc = _access("test", 0);

            return rc;
         }''',
      define_name='HAVE__ACCESS',
      execute=0,
      define_ret=0,
      msg='Checking for _access')

