/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_photon_serializer_StringSerializer */

#ifndef _Included_org_photon_serializer_StringSerializer
#define _Included_org_photon_serializer_StringSerializer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_photon_serializer_StringSerializer
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_photon_serializer_StringSerializer_initIDs
  (JNIEnv *, jclass);

/*
 * Class:     org_photon_serializer_StringSerializer
 * Method:    psoPackObject
 * Signature: (Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_photon_serializer_StringSerializer_psoPackObject
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_photon_serializer_StringSerializer
 * Method:    psoUnpackObject
 * Signature: ([B)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_photon_serializer_StringSerializer_psoUnpackObject
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     org_photon_serializer_StringSerializer
 * Method:    psoValidate
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_org_photon_serializer_StringSerializer_psoValidate
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
