/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_photon_serializer_SerializerErrors */

#ifndef _Included_org_photon_serializer_SerializerErrors
#define _Included_org_photon_serializer_SerializerErrors
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
