#! /usr/bin/env python
# encoding: utf-8
# :mode=python:  - For jedit

# Copyright (C) 2009 Daniel Prevost <dprevost@photonsoftware.org>
#  
# This file is free software; as a special exception the author gives
# unlimited permission to copy and/or distribute it, with or without 
# modifications, as long as this notice is preserved.
# 
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY, to the extent permitted by law; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

subdirs_list = [
        'Common', 'Nucleus', 'Quasar', 'API', 'Tools', 'Java']

def build(bld):
   bld.add_subdirs( subdirs_list )

   top_bld_debug = bld.srcnode.abspath(bld.env)
   top_bld_release = bld.srcnode.abspath(bld.env_of_name('release'))
   top_src = bld.srcnode.abspath()

   obj1_debug = bld.new_task_gen('subst')
   obj1_debug.source = 'LaunchQuasar.sh.in'
   obj1_debug.target = 'LaunchQuasar.sh'
   obj1_debug.dict   = {'BUILD_DIR': top_bld_debug, 'SRC_DIR': top_src}
   obj1_debug.chmod  = 0755
   
   obj1_release = obj1_debug.clone('release')
   obj1_release.dict   = {'BUILD_DIR': top_bld_release, 'SRC_DIR': top_src}

   obj2_debug = bld.new_task_gen('subst')
   obj2_debug.source = 'LaunchQuasarKeep.sh.in'
   obj2_debug.target = 'LaunchQuasarKeep.sh'
   obj2_debug.dict   = {'BUILD_DIR': top_bld_debug, 'SRC_DIR': top_src}
   obj2_debug.chmod  = 0755
   
   obj2_release = obj2_debug.clone('release')
   obj2_release.dict   = {'BUILD_DIR': top_bld_release, 'SRC_DIR': top_src}


